hello_caht/config/routes.rb
Rails.application.routes.draw do
  resources :mentions, only: [:new, :create, :index, :edit, :update, :destroy] do
    collection do
      post :confirm
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

hello_caht/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

hello_caht/app/models/mention.rb
class Mention < ApplicationRecord
  validates :content, presence: true, length: { minimum: 1, maximum: 140 }
end

hello_caht/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

hello_caht/app/controllers/mentions_controller.rb
class MentionsController < ApplicationController
  before_action :set_mention, only: [:edit, :update, :destroy]

  def new
    @mention = Mention.new
  end

  def confirm
    @mention = Mention.new(mention_params)
  end

  def create
    @mention = Mention.create(mention_params)
    if params[:back]
      render :new
    else
      if @mention.save
        redirect_to mentions_path, notice: "作成しました"
      else
        render :new
      end
    end
  end

  def index
    @mentions = Mention.all
  end

  def edit
  end

  def update
    if @mention.update(mention_params)
      redirect_to mentions_path, notice: "更新しました"
    else
      render :edit
    end
  end

  def destroy
    @mention.destroy
    redirect_to mentions_path, notice: "削除しました"
  end

  private

  def mention_params
    params.require(:mention).permit(:content)
  end

  def set_mention
    @mention = Mention.find(params[:id])
  end
end

hello_caht/app/helpers/application_helper.rb
module ApplicationHelper
end

hello_caht/app/helpers/mentions_helper.rb
module MentionsHelper
  def choose_new_or_edit
    if action_name == "new"
      confirm_mentions_path
    elsif action_name == "edit"
      mention_path
    end
  end
end

hello_caht/app/views/layouts/_footer.html.erb
<footer class="footer">
  <p class="text-muted">Hello Caht</p>
</footer>

hello_caht/app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#gnavi">
          <span class="sr-only">HelloCaht</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "HelloCaht", mentions_path, class: "navbar-brand" %>
      </div>
      <div id="gnavi" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li><%= link_to "発言一覧", mentions_path %></li>
          <li><%= link_to "発言作成", new_mention_path %></li>
        </ul>
      </div>
    </div>
  </nav>
</header>

hello_caht/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>HelloCaht</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%= render 'layouts/header' %>
  <div class="main container">
    <%= yield %>
  </div>
  <%= render 'layouts/footer' %>
</body>

</html>

hello_caht/app/views/mentions/_form.html.erb
<%= form_with(model: @mention, local: true,url: choose_new_or_edit , class: "mention") do |f| %>

<% if @mention.errors.any? %>
<div id="error_explanation">
  <h2><%= @mention.errors.count %>件のエラーがあります。</h2>
  <ul>
    <% @mention.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="mention">
  <ul>
    <li>
      <%= f.label "発言" %>
      <%= f.text_field :content %>
    </li>
    <li>
      <%= f.submit class: "submit" %>
    </li>
  </ul>

</div>



<% end %>

hello_caht/app/views/mentions/confirm.html.erb
<h3>以下の内容で、送信する。</h3>
<%= form_with(model: @mention, url: mentions_path, local: true) do |form| %>
<%= form.hidden_field :content %>
<p>Content:<%= @mention.content %></p>
<%= form.submit  "登録する" %>
<%= form.submit "戻る", name: 'back' %>
<% end %>

hello_caht/app/views/mentions/edit.html.erb
<h1>発言編集</h1>
<%= render 'form'%>

hello_caht/app/views/mentions/index.html.erb
<h1>発言一覧</h1>

<p><%= notice %> </p>
<table class="table table-striped">
  <thead>
    <tr>
      <th>発言</th>
      <th>発言時間</th>
    </tr>
  </thead>
  <tbody>
    <% @mentions.each  do |mention| %>
    <tr>
      <td><%= mention.content %></td>
      <td><%= mention.created_at.to_s(:datetime)  %></td>
      <td><%= link_to "編集する", edit_mention_path(mention.id) %></td>
      <td><%= link_to "削除する", mention_path(mention.id), method: :delete ,data: { confirm: '本当に削除していいですか？' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

hello_caht/app/views/mentions/new.html.erb
<h1>発言作成</h1>
<%= render 'form'%>